
CREATE DATABASE STUDIO;

CREATE TABLE STU_INSTRUTOR(
INS_ID INT PRIMARY KEY,
INS_NOME VARCHAR(45),
INS_SENHA VARCHAR(10)
);

CREATE TABLE STU_TURMA(
TUR_ID INT PRIMARY KEY,
TUR_HORARIO DATETIME,
TUR_ALU_NOME VARCHAR(45),
FOREIGN KEY(TUR_ALU_NOME) REFERENCES STU_ALUNOS(ALU_NOME)
);

CREATE TABLE STU_ALUNOS(
ALU_CPF VARCHAR(14) PRIMARY KEY,
ALU_NOME VARCHAR(45),
ALU_ENDERECO VARCHAR(45),
ALU_TELEFONE VARCHAR(15)
ALU_GMU_NOME VARCHAR(45),
FOREIGN KEY (ALU_GMU_NOME) REFERENCES STU_GMUSCULAR(GMU_NOME)
);

CREATE TABLE STU_GMUSCULAR(
GMU_ID INT PRIMARY KEY,
GMU_EXERCICIO VARCHAR(100)
GMU_NOME VARCHAR (45)
);
